<?php

return [
    'GATEWAY_BASE_URL' => env('GATEWAY_BASE_URL', ''),
    'GATEWAY_MERCHANT_ID' => env('GATEWAY_MERCHANT_ID', ''),
    'GATEWAY_API_PASSWORD' => env('GATEWAY_API_PASSWORD', ''),
    'GATEWAY_DEFAULT_CURRENCY' => env('GATEWAY_DEFAULT_CURRENCY', 'USD'),
    'GATEWAY_API_VERSION' => env('GATEWAY_API_VERSION', ''),
];
